ALTER TABLE users
    ADD COLUMN IF NOT EXISTS daily_reminder_hour SMALLINT NOT NULL DEFAULT 9,
    ADD COLUMN IF NOT EXISTS intraday_min_due SMALLINT NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS intraday_idle_hours SMALLINT NOT NULL DEFAULT 2,
    ADD COLUMN IF NOT EXISTS intraday_interval_minutes SMALLINT NOT NULL DEFAULT 180,
    ADD COLUMN IF NOT EXISTS quiet_hours_start SMALLINT NOT NULL DEFAULT 22,
    ADD COLUMN IF NOT EXISTS quiet_hours_end SMALLINT NOT NULL DEFAULT 9;

